# Generated by Django 4.0.4 on 2022-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
